Divide commands and functions
Europeia/recruitment-tool pull request #1
Opened 2023-04-08 23:22 UTC by brrscc

Moved all of the command definitions, listeners, and input/context validations to commander.py

Kept all of the backend/data operations in recruit.py

2023-04-09 08:04 UTC, Darcness requested changes

2023-04-09 08:04 UTC, Darcness commented on commander.py
> +class commander(commands.Cog):
https://peps.python.org/pep-0008/#class-names
Please and thank you.

2023-04-09 08:04 UTC, Darcness commented on commander.py
> +    @commands.hybrid_command(name="register", with_app_command=True,
What line length is being enforced here? This seems kind of short.

2023-04-09 08:04 UTC, Darcness commented on recruit.py
If you're going to perform this level of separation, then recruit shouldn't be a cog.  'Commander' is your cog and entry point, and the Discord objects that are necessary are fed to Recruit.

Also... how does any of this work if you're still loading the 'recruit' cog in main.py?

2023-04-11 19:56 UTC, Darcness commented on recruit.py
I think most of this type of restructure has been done by UPC already.  Is there anything in this PR we want to keep?

2023-04-11 22:20 UTC, nsupc reviewed
@brrscc are we good to close this, or is any of the functionality you added missing from main?

2023-04-11 23:53 UTC, closed without merging